project_id = "zafzwayqhlnxpsumfjps"

[functions.process-email-queue]
verify_jwt = true

[functions.send-email]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.sync-content-index]
verify_jwt = false

[functions.scrape-website]
verify_jwt = false